application: bowl-challenge
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: bowl.app

- url: /player/.*
  script: bowl.app
  login: required

- url: /public/.*
  script: bowl.app

libraries:
- name: jinja2
  version: latest
